export const permissionLabels: Record<string, string> = {
  'account:add': '新增软件账号',
  'account:advanced_filter': '高级筛选',
  'account:assign_user': '分配用户',
  'account:authorize_mcn': '授权 MCN',
  'account:batch_edit_commission_rate': '批量修改分成比例',
  'account:batch_invite': '批量邀请',
  'account:batch_open_spark': '批量开通星火',
  'account:batch_query_records': '批量查询记录',
  'account:control': '账号控制',
  'account:delete': '删除账号',
  'account:direct_invite': '直接邀请',
  'account:edit_commission_rate': '修改分成比例',
  'account:file_batch': '文件批量导入',
  'account:group_manager': '分组管理',
  'account:import': '导入账号',
  'account:invitation_records': '邀请记录',
  'account:open_spark': '开通星火',
  'account:refresh': '刷新账号',
  'account:remove_group': '移出分组',
  'account:set_group': '设置分组',
  'account:sync_auth': '同步授权',
  'account:unauthorize_mcn': '取消 MCN 授权',
  'account:update_income': '更新收益',
  account_drama_mode: '短剧模式',
  browser_accounts: '浏览器账号',
  drama_favorite: '短剧收藏',
  drama_mode: '短剧模式',
  drama_mode2: '短剧模式 2',
  elf_film_cxt: '橙星推短剧',
  elf_film_tv: '影视短剧',
  elf_film_tv_activity: '影视活动',
  elf_firefly_plan: '萤光计划',
  elf_goods_delivery: '商品交付',
  elf_spark_plan: '星火计划',
  firefly_plan: '萤光计划',
  income_query: '收益查询',
  task_history: '任务历史',
  task_queue: '任务队列',
  video_collection: '视频收藏',
  user_alipay_info: '支付宝信息',
  user_alipay_stats: '支付宝统计',
  user_assign_operator: '分配运营',
  user_bindings: '账号绑定',
  user_change_role: '修改角色',
  user_commission_visibility: '分成可见性',
  user_cooperation_type: '合作类型',
  user_create_captain: '创建队长',
  user_delete: '删除用户',
  user_edit: '编辑用户',
  user_edit_commission_rate: '修改用户分成',
  user_level: '用户等级',
  user_oem_setting: 'OEM 设置',
  user_quota: '账号额度',
  user_reset_password: '重置密码',
  user_simulation_mode: '模拟模式',
  user_toggle_status: '启用/禁用用户',
  user_update_org_cookie: '更新机构 Cookie',
  'page:account-violation': '账号违规信息',
  'page:accounts': '软件账号管理',
  'page:cloud-cookies': '云端 Cookie 管理',
  'page:collect-pool': '短剧收藏池',
  'page:cxt-user': '橙星推用户',
  'page:cxt-videos': '橙星推剧集',
  'page:dashboard': '概览仪表盘',
  'page:drama-collections': '短剧收藏记录',
  'page:drama-statistics': '短剧链接统计',
  'page:external-url-stats': '外部项目统计',
  'page:firefly-income': '历史收益',
  'page:firefly-members': '萤光本月收益',
  'page:fluorescent-income': '收益明细',
  'page:high-income-dramas': '高转化短剧管理',
  'page:ks-accounts': 'KS 账号管理',
  'page:org-members': '机构成员管理',
  'page:settings': '系统配置',
  'page:spark-archive': '星火历史收益',
  'page:spark-income': '星火收益',
  'page:spark-members': '星火成员',
  'page:spark-photos': '星火作品',
  'page:spark-violation-dramas': '星火违规短剧',
  'page:spark-violation-photos': '星火违规作品',
  'page:statistics': '执行统计',
  'page:users': '用户管理',
  'page:wallet-info': '钱包信息',
}

export function permissionLabel(item: { key?: string; perm_key?: string; name?: string; label?: string; title?: string }) {
  const code = item.key || item.perm_key || ''
  return item.label || item.name || item.title || permissionLabels[code] || code
}
